services:
  db:
    image: postgres:13
    ports:
      - 54324:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: mintery

  quepasa:
    image: ghcr.io/tzconnectberlin/que-pasa:1.1.0
    entrypoint: |-
      bash -c '
        set -e -x

        while ! psql -d "$$DATABASE_URL" -c "select 1" ; do
          sleep 1
        done

        /que-pasa/que-pasa --bcd-enable
      '
    volumes:
      - ./config:/config
    links:
      - db
    environment:
      DATABASE_URL: postgres://pguser:pgpass@db:5432/mintery
      CONTRACT_SETTINGS: /config/quepasa_config.yaml
      NODE_URL: http://art-basel.tzconnect.berlin:18732
      BCD_NETWORK: hangzhou2net

  peppermint:
    image: ghcr.io/tzconnectberlin/peppermint:1.1
    entrypoint: |-
      bash -c '
        set -e -x

        while ! psql -d "$$DATABASE_URL" -c "select 1" ; do
          sleep 1
        done

        psql -d "$$DATABASE_URL" < database/schema.sql

        node app.mjs
      '
    environment:
      DATABASE_URL: postgres://pguser:pgpass@db:5432/mintery
    links:
      - db
    volumes:
      - ./config/peppermint_config.json:/build/config.json
